<a href="https://colab.research.google.com/github/Abdulmukhtor/ML-Supervised--learning-2-bolim/blob/main/Colaboratory%EC%97%90_%EC%98%A4%EC%8B%A0_%EA%B2%83%EC%9D%84_%ED%99%98%EC%98%81%ED%95%A9%EB%8B%88%EB%8B%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Loyihalar tahlili

In [ ]:
!git clone https://github.com/Abdulmukhtor/ML-Supervised--learning-2-bolim/blob/main/1-dars%20vazifa/Bank_Personal_Loan_Modelling.csv

Cloning into 'Bank_Personal_Loan_Modelling.csv'...
fatal: repository 'https://github.com/Abdulmukhtor/ML-Supervised--learning-2-bolim/blob/main/1-dars%20vazifa/Bank_Personal_Loan_Modelling.csv/' not found

In [ ]:
import pandas as pd

# urlda raw yozilishining sababi githubdagi fayllarning asosiy (default) URLsi veb-sahifa  ko'rinishida bo'ladi , bu esa pandas.read_csv()da o'qilamydi
url = "https://raw.githubusercontent.com/Abdulmukhtor/ML-Supervised--learning-2-bolim/main/1-dars%20vazifa/Bank_Personal_Loan_Modelling.csv"
#"Raw" versiya — bu faqat faylning o‘zini ko‘rsatadigan URL. Uni GitHub interfeysidan olish mumkin
df = pd.read_csv(url)  # yangilangan URL
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

KUTUBXONALARNI yuklab olish

In [ ]:
!pip install zipcodes
!pip install pgeocode
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pgeocode
from sklearn.model_selection import train_test_split, KFold, cross_val_score , GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,confusion_matrix,precision_score,jaccard_score,recall_score,f1_score,fbeta_score, make_scorer,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB,MultinomialNB,ComplementNB
from sklearn.neighbors import KNeighborsClassifier
from imblearn.over_sampling import SMOTE , ADASYN
from imblearn.under_sampling import TomekLinks , EditedNearestNeighbours
from imblearn.pipeline import Pipeline
from sklearn import metrics
import warnings
warnings.filterwarnings("ignore")
os.environ["PYTHONWARNINGS"] = "ignore"

Requirement already satisfied: zipcodes in /usr/local/lib/python3.11/dist-packages (1.3.0)
Requirement already satisfied: pgeocode in /usr/local/lib/python3.11/dist-packages (0.5.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from pgeocode) (2.32.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pgeocode) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from pgeocode) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->pgeocode) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->pgeocode) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->pgeocode) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->pgeocode) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->pgeocode) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->pgeocode) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->pgeocode) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->pgeocode) (1.17.0)

Data Pre Processing

In [ ]:
#Ma'lumotlar jadvali tuzish

df = pd.DataFrame(df)
df

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,29,3,40,92697,1,1.9,3,0,0,0,0,1,0
4996,4997,30,4,15,92037,4,0.4,1,85,0,0,0,1,0
4997,4998,63,39,24,93023,2,0.3,3,0,0,0,0,0,0
4998,4999,65,40,49,90034,3,0.5,2,0,0,0,0,1,0
4999,5000,28,4,83,92612,3,0.8,1,0,0,0,0,1,1

In [ ]:
# Kearaksiz ustunlarni tashlab yuborish

df.drop(['ID'],axis=1,inplace =True)
df

,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,35,8,45,91330,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,92697,1,1.9,3,0,0,0,0,1,0
4996,30,4,15,92037,4,0.4,1,85,0,0,0,1,0
4997,63,39,24,93023,2,0.3,3,0,0,0,0,0,0
4998,65,40,49,90034,3,0.5,2,0,0,0,0,1,0
4999,28,4,83,92612,3,0.8,1,0,0,0,0,1,1

In [ ]:
# Qayta takrorlangan elementlarni chiqarish

print(len(df[df.duplicated()]))

0

In [ ]:
# tushib qolgan qiymatlarni tekshirish

df.isna().sum()

Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [ ]:
df.isnull().sum()

Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 5000 non-null   int64
 1   Experience          5000 non-null   int64
 2   Income              5000 non-null   int64
 3   ZIP Code            5000 non-null   int64
 4   Family              5000 non-null   int64
 5   CCAvg               5000 non-null   float64
 6   Education           5000 non-null   int64
 7   Mortgage            5000 non-null   int64
 8   Personal Loan       5000 non-null   int64
 9   Securities Account  5000 non-null   int64
 10  CD Account          5000 non-null   int64
 11  Online              5000 non-null   int64
 12  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(12)
memory usage: 507.9 KB

In [ ]:
# dataset haqida umumiy ma'lumotni chiqarish
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,5000.0,45.338400,11.463166,23.0,35.0,45.0,55.0,67.0
Experience,5000.0,20.104600,11.467954,-3.0,10.0,20.0,30.0,43.0
Income,5000.0,73.774200,46.033729,8.0,39.0,64.0,98.0,224.0
ZIP Code,5000.0,93152.503000,2121.852197,9307.0,91911.0,93437.0,94608.0,96651.0
Family,5000.0,2.396400,1.147663,1.0,1.0,2.0,3.0,4.0
CCAvg,5000.0,1.937938,1.747659,0.0,0.7,1.5,2.5,10.0
Education,5000.0,1.881000,0.839869,1.0,1.0,2.0,3.0,3.0
Mortgage,5000.0,56.498800,101.713802,0.0,0.0,0.0,101.0,635.0
Personal Loan,5000.0,0.096000,0.294621,0.0,0.0,0.0,0.0,1.0
Securities Account,5000.0,0.104400,0.305809,0.0,0.0,0.0,0.0,1.0
CD Account,5000.0,0.060400,0.238250,0.0,0.0,0.0,0.0,1.0
Online,5000.0,0.596800,0.490589,0.0,0.0,1.0,1.0,1.0
CreditCard,5000.0,0.294000,0.455637,0.0,0.0,0.0,1.0,1.0

In [26]:
# biz bu yerda "Experience" ustunida "min" qiymatida manfiy qiymat borligini ko'rishimiz mumkin
# biz buni numpy kutubxonasining "abs" funksiyasi orqali musbat qiymatga aylantiramiz, chunki tajriba doimo o'suvchi musbat qiymat

df['Experience'] = df['Experience'].abs()

In [27]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,5000.0,45.338400,11.463166,23.0,35.0,45.0,55.0,67.0
Experience,5000.0,20.134600,11.415189,0.0,10.0,20.0,30.0,43.0
Income,5000.0,73.774200,46.033729,8.0,39.0,64.0,98.0,224.0
ZIP Code,5000.0,93152.503000,2121.852197,9307.0,91911.0,93437.0,94608.0,96651.0
Family,5000.0,2.396400,1.147663,1.0,1.0,2.0,3.0,4.0
CCAvg,5000.0,1.937938,1.747659,0.0,0.7,1.5,2.5,10.0
Education,5000.0,1.881000,0.839869,1.0,1.0,2.0,3.0,3.0
Mortgage,5000.0,56.498800,101.713802,0.0,0.0,0.0,101.0,635.0
Personal Loan,5000.0,0.096000,0.294621,0.0,0.0,0.0,0.0,1.0
Securities Account,5000.0,0.104400,0.305809,0.0,0.0,0.0,0.0,1.0
CD Account,5000.0,0.060400,0.238250,0.0,0.0,0.0,0.0,1.0
Online,5000.0,0.596800,0.490589,0.0,0.0,1.0,1.0,1.0
CreditCard,5000.0,0.294000,0.455637,0.0,0.0,0.0,1.0,1.0
Experince,5000.0,20.134600,11.415189,0.0,10.0,20.0,30.0,43.0